// Code generated by protoc-gen-go. DO NOT EDIT.
// source: io/common/integration.proto

package io

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IntegrationStatus int32

const (
	IntegrationStatus_INTEGRATION_DISABLED IntegrationStatus = 0
	IntegrationStatus_INTEGRATION_ACTIVE   IntegrationStatus = 1
)

var IntegrationStatus_name = map[int32]string{
	0: "INTEGRATION_DISABLED",
	1: "INTEGRATION_ACTIVE",
}

var IntegrationStatus_value = map[string]int32{
	"INTEGRATION_DISABLED": 0,
	"INTEGRATION_ACTIVE":   1,
}

func (x IntegrationStatus) String() string {
	return proto.EnumName(IntegrationStatus_name, int32(x))
}

func (IntegrationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de96aa3e87c64e2a, []int{0}
}

type IntegrationType int32

const (
	IntegrationType_INTEGRATION_MYSQL IntegrationType = 0
)

var IntegrationType_name = map[int32]string{
	0: "INTEGRATION_MYSQL",
}

var IntegrationType_value = map[string]int32{
	"INTEGRATION_MYSQL": 0,
}

func (x IntegrationType) String() string {
	return proto.EnumName(IntegrationType_name, int32(x))
}

func (IntegrationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de96aa3e87c64e2a, []int{1}
}

type Integration struct {
	Name   string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status IntegrationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=io.IntegrationStatus" json:"status,omitempty"`
	// Types that are valid to be assigned to Configuration:
	//	*Integration_SqlConfiguration
	Configuration        isIntegration_Configuration `protobuf_oneof:"Configuration"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Integration) Reset()         { *m = Integration{} }
func (m *Integration) String() string { return proto.CompactTextString(m) }
func (*Integration) ProtoMessage()    {}
func (*Integration) Descriptor() ([]byte, []int) {
	return fileDescriptor_de96aa3e87c64e2a, []int{0}
}

func (m *Integration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Integration.Unmarshal(m, b)
}
func (m *Integration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Integration.Marshal(b, m, deterministic)
}
func (m *Integration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Integration.Merge(m, src)
}
func (m *Integration) XXX_Size() int {
	return xxx_messageInfo_Integration.Size(m)
}
func (m *Integration) XXX_DiscardUnknown() {
	xxx_messageInfo_Integration.DiscardUnknown(m)
}

var xxx_messageInfo_Integration proto.InternalMessageInfo

func (m *Integration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Integration) GetStatus() IntegrationStatus {
	if m != nil {
		return m.Status
	}
	return IntegrationStatus_INTEGRATION_DISABLED
}

type isIntegration_Configuration interface {
	isIntegration_Configuration()
}

type Integration_SqlConfiguration struct {
	SqlConfiguration *SqlConfiguration `protobuf:"bytes,3,opt,name=sqlConfiguration,proto3,oneof"`
}

func (*Integration_SqlConfiguration) isIntegration_Configuration() {}

func (m *Integration) GetConfiguration() isIntegration_Configuration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

func (m *Integration) GetSqlConfiguration() *SqlConfiguration {
	if x, ok := m.GetConfiguration().(*Integration_SqlConfiguration); ok {
		return x.SqlConfiguration
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Integration) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Integration_SqlConfiguration)(nil),
	}
}

type SqlConfiguration struct {
	ServerId             string   `protobuf:"bytes,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	ServerName           string   `protobuf:"bytes,2,opt,name=serverName,proto3" json:"serverName,omitempty"`
	Host                 string   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	User                 string   `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	DbName               string   `protobuf:"bytes,7,opt,name=dbName,proto3" json:"dbName,omitempty"`
	TableName            string   `protobuf:"bytes,8,opt,name=tableName,proto3" json:"tableName,omitempty"`
	PrimaryKeyColumn     string   `protobuf:"bytes,9,opt,name=primaryKeyColumn,proto3" json:"primaryKeyColumn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqlConfiguration) Reset()         { *m = SqlConfiguration{} }
func (m *SqlConfiguration) String() string { return proto.CompactTextString(m) }
func (*SqlConfiguration) ProtoMessage()    {}
func (*SqlConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_de96aa3e87c64e2a, []int{1}
}

func (m *SqlConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlConfiguration.Unmarshal(m, b)
}
func (m *SqlConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlConfiguration.Marshal(b, m, deterministic)
}
func (m *SqlConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlConfiguration.Merge(m, src)
}
func (m *SqlConfiguration) XXX_Size() int {
	return xxx_messageInfo_SqlConfiguration.Size(m)
}
func (m *SqlConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_SqlConfiguration proto.InternalMessageInfo

func (m *SqlConfiguration) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *SqlConfiguration) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *SqlConfiguration) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *SqlConfiguration) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *SqlConfiguration) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *SqlConfiguration) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SqlConfiguration) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *SqlConfiguration) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *SqlConfiguration) GetPrimaryKeyColumn() string {
	if m != nil {
		return m.PrimaryKeyColumn
	}
	return ""
}

func init() {
	proto.RegisterEnum("io.IntegrationStatus", IntegrationStatus_name, IntegrationStatus_value)
	proto.RegisterEnum("io.IntegrationType", IntegrationType_name, IntegrationType_value)
	proto.RegisterType((*Integration)(nil), "io.Integration")
	proto.RegisterType((*SqlConfiguration)(nil), "io.SqlConfiguration")
}

func init() { proto.RegisterFile("io/common/integration.proto", fileDescriptor_de96aa3e87c64e2a) }

var fileDescriptor_de96aa3e87c64e2a = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x6e, 0x42, 0x29, 0xeb, 0x99, 0x46, 0x33, 0x6b, 0x9b, 0xa2, 0x81, 0x50, 0x35, 0x71, 0x11,
	0x55, 0x34, 0x96, 0xc6, 0x3d, 0x52, 0xdb, 0x55, 0x10, 0x75, 0x94, 0x91, 0x56, 0x48, 0x70, 0x83,
	0xdc, 0xc6, 0x64, 0xd6, 0x1a, 0x9f, 0x60, 0xbb, 0x4c, 0x7d, 0x03, 0x5e, 0x84, 0x1b, 0x9e, 0x12,
	0xd9, 0x29, 0x5b, 0xb6, 0xde, 0x7d, 0xe7, 0xfb, 0x39, 0x3f, 0x96, 0xe1, 0x85, 0x40, 0xba, 0xc4,
	0xa2, 0x40, 0x49, 0x85, 0x34, 0x3c, 0x57, 0xcc, 0x08, 0x94, 0x71, 0xa9, 0xd0, 0x20, 0xf1, 0x05,
	0x9e, 0xbe, 0x71, 0x70, 0xd9, 0xcf, 0xb9, 0xec, 0xeb, 0x5b, 0x96, 0xe7, 0x5c, 0x51, 0x2c, 0xad,
	0x49, 0x53, 0x26, 0x25, 0x1a, 0x17, 0xd0, 0x55, 0xe2, 0xec, 0x8f, 0x07, 0xfb, 0xc9, 0x7d, 0x1f,
	0x42, 0xa0, 0x29, 0x59, 0xc1, 0x43, 0xaf, 0xeb, 0x45, 0xed, 0xd4, 0x61, 0xd2, 0x87, 0x96, 0x36,
	0xcc, 0xac, 0x75, 0xe8, 0x77, 0xbd, 0xe8, 0xf9, 0xf9, 0x71, 0x2c, 0x30, 0xae, 0x85, 0x66, 0x4e,
	0x4c, 0xb7, 0x26, 0x32, 0x84, 0x40, 0xff, 0x5c, 0x8d, 0x50, 0xfe, 0x10, 0xf9, 0xba, 0x72, 0x84,
	0x4f, 0xba, 0x5e, 0xb4, 0x7f, 0x7e, 0x64, 0x83, 0xb3, 0x47, 0xda, 0x87, 0x46, 0xba, 0xe3, 0x1f,
	0x76, 0xe0, 0xe0, 0x01, 0x71, 0xf6, 0xdb, 0x87, 0xe0, 0x71, 0x92, 0x9c, 0xc2, 0x9e, 0xe6, 0xea,
	0x17, 0x57, 0x49, 0xb6, 0x5d, 0xf8, 0xae, 0x26, 0xaf, 0x00, 0x2a, 0x3c, 0xb5, 0xe7, 0xf8, 0x4e,
	0xad, 0x31, 0xf6, 0xd0, 0x6b, 0xd4, 0xc6, 0x6d, 0xd6, 0x4e, 0x1d, 0xb6, 0x5c, 0x89, 0xca, 0x84,
	0xcd, 0xae, 0x17, 0x1d, 0xa4, 0x0e, 0x5b, 0x6e, 0xad, 0xb9, 0x0a, 0x9f, 0x56, 0x3e, 0x8b, 0xed,
	0xdc, 0x92, 0x69, 0x7d, 0x8b, 0x2a, 0x0b, 0x5b, 0xd5, 0xdc, 0xff, 0x35, 0x39, 0x81, 0x56, 0xb6,
	0x70, 0x33, 0x9f, 0x39, 0x65, 0x5b, 0x91, 0x97, 0xd0, 0x36, 0x6c, 0xb1, 0xe2, 0x4e, 0xda, 0x73,
	0xd2, 0x3d, 0x41, 0x7a, 0x10, 0x94, 0x4a, 0x14, 0x4c, 0x6d, 0x26, 0x7c, 0x33, 0xc2, 0xd5, 0xba,
	0x90, 0x61, 0xdb, 0x99, 0x76, 0xf8, 0xde, 0x18, 0x0e, 0x77, 0x1e, 0x9f, 0x84, 0x70, 0x94, 0x4c,
	0xe7, 0xe3, 0xf7, 0xe9, 0x60, 0x9e, 0x7c, 0x9a, 0x7e, 0xbf, 0x48, 0x66, 0x83, 0xe1, 0xe5, 0xf8,
	0x22, 0x68, 0x90, 0x13, 0x20, 0x75, 0x65, 0x30, 0x9a, 0x27, 0x5f, 0xc6, 0x81, 0xd7, 0x8b, 0xa0,
	0x53, 0x6b, 0x33, 0xdf, 0x94, 0x9c, 0x1c, 0xc3, 0x61, 0xdd, 0xfa, 0xf1, 0xeb, 0xec, 0xf3, 0x65,
	0xd0, 0x18, 0xbe, 0x83, 0x8e, 0xc0, 0xd8, 0x5e, 0x78, 0x23, 0x4c, 0x7c, 0x35, 0x11, 0xf8, 0xed,
	0xb5, 0x36, 0x4c, 0x5f, 0xdf, 0x71, 0x4b, 0x2c, 0xa8, 0x40, 0x5a, 0x60, 0xc6, 0x57, 0x54, 0x67,
	0x37, 0x34, 0x47, 0x2a, 0xf0, 0xaf, 0xdf, 0xbc, 0x9a, 0x24, 0xb8, 0x68, 0xb9, 0xaf, 0xf6, 0xf6,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x22, 0x86, 0xb7, 0x1c, 0xbb, 0x02, 0x00, 0x00,
}
