// Code generated by protoc-gen-go. DO NOT EDIT.
// source: io/common/project.proto

package io

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProjectStatus int32

const (
	// Zero based enum, don't use 0.
	ProjectStatus_NO_PROJECT_STATUS ProjectStatus = 0
	// Active projects allow for creation of records (turned on by default).
	ProjectStatus_PROJECT_ACTIVE_FOR_OBJECT_CREATION ProjectStatus = 1
	// Disabled projects do not allow for creation of records (i.e. temporarily disable enroling of members / creating of coupons, etc).
	ProjectStatus_PROJECT_DISABLED_FOR_OBJECT_CREATION ProjectStatus = 2
	// Default status for all projects. A draft project can do everything a published program can:
	// Cards can be created, stats will show up, etc.
	// Data belonging to draft projects is automatically purged every 7 days.
	// A draft project uses a PassKit Apple Developer Certificate, and has a PassKit legal disclaimer on the back.
	// Draft projects cannot be used for a production setup.
	ProjectStatus_PROJECT_DRAFT ProjectStatus = 4
	// A project can only be published if a custom Apple Developer Certificate is uploaded, if payment details have been provided,
	// and an account email address has been validated.
	// Published projects do not have a PassKit legal disclaimer on the back.
	// Published projects do not have their data purged on a 7 day basis.
	ProjectStatus_PROJECT_PUBLISHED ProjectStatus = 8
	// A project is private: records can only by created by authorized users / via the portal interface.
	ProjectStatus_PROJECT_PRIVATE ProjectStatus = 16
	// The project is currently over quota, and new records cannot be created (set by system only; cannot be set by user)
	ProjectStatus_PROJECT_OVER_QUOTA ProjectStatus = 32
	// A project which needs to be deleted. If delete flag is set, project will be deleted in the near future.
	ProjectStatus_PROJECT_DELETED ProjectStatus = 64
)

var ProjectStatus_name = map[int32]string{
	0:  "NO_PROJECT_STATUS",
	1:  "PROJECT_ACTIVE_FOR_OBJECT_CREATION",
	2:  "PROJECT_DISABLED_FOR_OBJECT_CREATION",
	4:  "PROJECT_DRAFT",
	8:  "PROJECT_PUBLISHED",
	16: "PROJECT_PRIVATE",
	32: "PROJECT_OVER_QUOTA",
	64: "PROJECT_DELETED",
}

var ProjectStatus_value = map[string]int32{
	"NO_PROJECT_STATUS":                    0,
	"PROJECT_ACTIVE_FOR_OBJECT_CREATION":   1,
	"PROJECT_DISABLED_FOR_OBJECT_CREATION": 2,
	"PROJECT_DRAFT":                        4,
	"PROJECT_PUBLISHED":                    8,
	"PROJECT_PRIVATE":                      16,
	"PROJECT_OVER_QUOTA":                   32,
	"PROJECT_DELETED":                      64,
}

func (x ProjectStatus) String() string {
	return proto.EnumName(ProjectStatus_name, int32(x))
}

func (ProjectStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a8ef3e8cce3ff548, []int{0}
}

type Project struct {
	// The PassProtocol the project implements.
	Protocol PassProtocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=io.PassProtocol" json:"protocol,omitempty"`
	// The class ID that the projects refers to (highest level protocol object; i.e. member program id, coupon campaign id, etc).
	ClassId string `protobuf:"bytes,2,opt,name=classId,proto3" json:"classId,omitempty"`
	// The project name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The project short-code; used for creating public project URL's.
	ShortCode string `protobuf:"bytes,4,opt,name=shortCode,proto3" json:"shortCode,omitempty"`
	// The timestamp when the project was created.
	Created              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8ef3e8cce3ff548, []int{0}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetProtocol() PassProtocol {
	if m != nil {
		return m.Protocol
	}
	return PassProtocol_RAW_PROTOCOL
}

func (m *Project) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetShortCode() string {
	if m != nil {
		return m.ShortCode
	}
	return ""
}

func (m *Project) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type ProjectByShortCodeResult struct {
	Project              *Project      `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Template             *PassTemplate `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ProjectByShortCodeResult) Reset()         { *m = ProjectByShortCodeResult{} }
func (m *ProjectByShortCodeResult) String() string { return proto.CompactTextString(m) }
func (*ProjectByShortCodeResult) ProtoMessage()    {}
func (*ProjectByShortCodeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8ef3e8cce3ff548, []int{1}
}

func (m *ProjectByShortCodeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectByShortCodeResult.Unmarshal(m, b)
}
func (m *ProjectByShortCodeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectByShortCodeResult.Marshal(b, m, deterministic)
}
func (m *ProjectByShortCodeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectByShortCodeResult.Merge(m, src)
}
func (m *ProjectByShortCodeResult) XXX_Size() int {
	return xxx_messageInfo_ProjectByShortCodeResult.Size(m)
}
func (m *ProjectByShortCodeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectByShortCodeResult.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectByShortCodeResult proto.InternalMessageInfo

func (m *ProjectByShortCodeResult) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *ProjectByShortCodeResult) GetTemplate() *PassTemplate {
	if m != nil {
		return m.Template
	}
	return nil
}

type ProjectStatusFilter struct {
	Status               ProjectStatus `protobuf:"varint,2,opt,name=status,proto3,enum=io.ProjectStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ProjectStatusFilter) Reset()         { *m = ProjectStatusFilter{} }
func (m *ProjectStatusFilter) String() string { return proto.CompactTextString(m) }
func (*ProjectStatusFilter) ProtoMessage()    {}
func (*ProjectStatusFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8ef3e8cce3ff548, []int{2}
}

func (m *ProjectStatusFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectStatusFilter.Unmarshal(m, b)
}
func (m *ProjectStatusFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectStatusFilter.Marshal(b, m, deterministic)
}
func (m *ProjectStatusFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectStatusFilter.Merge(m, src)
}
func (m *ProjectStatusFilter) XXX_Size() int {
	return xxx_messageInfo_ProjectStatusFilter.Size(m)
}
func (m *ProjectStatusFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectStatusFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectStatusFilter proto.InternalMessageInfo

func (m *ProjectStatusFilter) GetStatus() ProjectStatus {
	if m != nil {
		return m.Status
	}
	return ProjectStatus_NO_PROJECT_STATUS
}

func init() {
	proto.RegisterEnum("io.ProjectStatus", ProjectStatus_name, ProjectStatus_value)
	proto.RegisterType((*Project)(nil), "io.Project")
	proto.RegisterType((*ProjectByShortCodeResult)(nil), "io.ProjectByShortCodeResult")
	proto.RegisterType((*ProjectStatusFilter)(nil), "io.ProjectStatusFilter")
}

func init() { proto.RegisterFile("io/common/project.proto", fileDescriptor_a8ef3e8cce3ff548) }

var fileDescriptor_a8ef3e8cce3ff548 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xd1, 0x6e, 0xd3, 0x3c,
	0x18, 0x86, 0xff, 0xf4, 0x2f, 0xeb, 0xe6, 0x6a, 0x5b, 0xea, 0x09, 0x08, 0x15, 0x12, 0x55, 0x35,
	0x50, 0x41, 0x28, 0x91, 0x0a, 0xc7, 0x68, 0x69, 0xeb, 0x8a, 0xb0, 0x6a, 0x09, 0x8e, 0xdb, 0x03,
	0x4e, 0xaa, 0x2c, 0x35, 0x9d, 0x59, 0xb2, 0x2f, 0x8a, 0xdd, 0x03, 0x6e, 0x89, 0x3b, 0xe0, 0x7e,
	0xb8, 0x10, 0x34, 0x27, 0x4e, 0x37, 0x89, 0xb3, 0xfa, 0x79, 0x1f, 0x7f, 0x5f, 0x5f, 0x07, 0x3d,
	0x17, 0xe0, 0xa5, 0x90, 0xe7, 0x70, 0xe7, 0x15, 0x25, 0xfc, 0xe0, 0xa9, 0x72, 0x8b, 0x12, 0x14,
	0xe0, 0x96, 0x80, 0xfe, 0xab, 0x2d, 0xc0, 0x36, 0xe3, 0x9e, 0x26, 0xd7, 0xbb, 0xef, 0x9e, 0x12,
	0x39, 0x97, 0x2a, 0xc9, 0x8b, 0x4a, 0xea, 0xbf, 0x78, 0x74, 0x5b, 0x41, 0x0a, 0x99, 0xac, 0x23,
	0x67, 0x1f, 0x29, 0x9e, 0x17, 0x59, 0xa2, 0x78, 0x95, 0x0c, 0x7f, 0x5b, 0xa8, 0x13, 0x55, 0xbb,
	0xf0, 0x7b, 0x74, 0x68, 0x2e, 0x3a, 0xd6, 0xc0, 0x1a, 0x9d, 0x8c, 0x6d, 0x57, 0x80, 0x1b, 0x25,
	0x52, 0x46, 0x35, 0xa7, 0x8d, 0x81, 0x1d, 0xd4, 0x49, 0xb3, 0x44, 0xca, 0x60, 0xe3, 0xb4, 0x06,
	0xd6, 0xe8, 0x88, 0x9a, 0x23, 0xc6, 0xa8, 0x7d, 0x97, 0xe4, 0xdc, 0xf9, 0x5f, 0x63, 0xfd, 0x1b,
	0xbf, 0x44, 0x47, 0xf2, 0x06, 0x4a, 0x35, 0x85, 0x0d, 0x77, 0xda, 0x3a, 0xd8, 0x03, 0xfc, 0x11,
	0x75, 0xd2, 0x92, 0x27, 0x8a, 0x6f, 0x9c, 0x27, 0x03, 0x6b, 0xd4, 0x1d, 0xf7, 0xdd, 0xaa, 0xad,
	0x6b, 0xda, 0xba, 0xcc, 0xb4, 0xa5, 0x46, 0x1d, 0x02, 0x72, 0xea, 0xbf, 0x3e, 0xf9, 0x19, 0x9b,
	0x59, 0x94, 0xcb, 0x5d, 0xa6, 0xf0, 0x6b, 0xd4, 0xa9, 0x9f, 0x50, 0x57, 0xe9, 0x8e, 0xbb, 0xba,
	0x4a, 0x85, 0xa8, 0xc9, 0xee, 0x2b, 0x9b, 0x07, 0xd1, 0x2d, 0xba, 0xfb, 0xca, 0xac, 0xe6, 0xb4,
	0x31, 0x86, 0x17, 0xe8, 0xac, 0x9e, 0x10, 0xab, 0x44, 0xed, 0xe4, 0x5c, 0x64, 0x8a, 0x97, 0xf8,
	0x2d, 0x3a, 0x90, 0xfa, 0xac, 0x47, 0x9c, 0x8c, 0x7b, 0x0f, 0x56, 0x55, 0x22, 0xad, 0x85, 0x77,
	0x7f, 0x2c, 0x74, 0xfc, 0x28, 0xc1, 0x4f, 0x51, 0xef, 0x2a, 0x5c, 0x47, 0x34, 0xfc, 0x42, 0xa6,
	0x6c, 0x1d, 0x33, 0x9f, 0x2d, 0x63, 0xfb, 0x3f, 0xfc, 0x06, 0x0d, 0x0d, 0xf3, 0xa7, 0x2c, 0x58,
	0x91, 0xf5, 0x3c, 0xa4, 0xeb, 0x70, 0xa2, 0xc9, 0x94, 0x12, 0x9f, 0x05, 0xe1, 0x95, 0x6d, 0xe1,
	0x11, 0x3a, 0x37, 0xde, 0x2c, 0x88, 0xfd, 0xc9, 0x82, 0xcc, 0xfe, 0x69, 0xb6, 0x70, 0x0f, 0x1d,
	0x37, 0x26, 0xf5, 0xe7, 0xcc, 0x6e, 0xdf, 0xef, 0x36, 0x28, 0x5a, 0x4e, 0x16, 0x41, 0xfc, 0x99,
	0xcc, 0xec, 0x43, 0x7c, 0x86, 0x4e, 0x1b, 0x4c, 0x83, 0x95, 0xcf, 0x88, 0x6d, 0xe3, 0x67, 0x08,
	0x1b, 0x18, 0xae, 0x08, 0x5d, 0x7f, 0x5d, 0x86, 0xcc, 0xb7, 0x07, 0x0f, 0xe5, 0x19, 0x59, 0x10,
	0x46, 0x66, 0xf6, 0xc5, 0xe4, 0x13, 0x3a, 0x15, 0xe0, 0x16, 0x89, 0x94, 0xb7, 0x42, 0xb9, 0xd1,
	0xa5, 0x80, 0x6f, 0xe7, 0x52, 0x25, 0xf2, 0xa6, 0x61, 0x29, 0xe4, 0x9e, 0x00, 0x2f, 0x87, 0x0d,
	0xcf, 0x3c, 0xb9, 0xb9, 0xf5, 0xb6, 0xe0, 0x09, 0xf8, 0xd5, 0x6a, 0x47, 0x97, 0x01, 0x5c, 0x1f,
	0xe8, 0xcf, 0xfe, 0xe1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xfc, 0xaf, 0xb3, 0x11, 0x03,
	0x00, 0x00,
}
