// Code generated by protoc-gen-go. DO NOT EDIT.
// source: io/flights/flight_designator.proto

package flights

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
	io "stash.passkit.com/io/model/sdk/go/io"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Flight alerts automatically update boarding passes as information becomes available or changes. Note that these services may incur additional usage charges.
type FlightAlerts int32

const (
	// Boarding passes will not automatically update.
	FlightAlerts_NO_ALERTS FlightAlerts = 0
	// Boarding passes will automatically update whenever a change to the departure gate/time, arrival gate/time or baggage belt information is detected.
	FlightAlerts_ALL_ALERTS FlightAlerts = 1
	// Boarding passes will automatically update whenever a change to the departure gate is detected.
	FlightAlerts_DEPARTURE_GATE_ALERT FlightAlerts = 2
	// Boarding passes will automatically update whenever a change to the estimated departure gate is detected.
	FlightAlerts_DEPARTURE_TIME_ALERT FlightAlerts = 4
	// Boarding passes will automatically update whenever a change to the arrival gate is detected.
	FlightAlerts_ARRIVAL_GATE_ALERT FlightAlerts = 8
	// Boarding passes will automatically update whenever a change to the estimated arrival time is detected.
	FlightAlerts_ARRIVAL_TIME_ALERT FlightAlerts = 16
	// Boarding passes will automatically update whenever the baggage collection belt or area is known or changes.
	FlightAlerts_BAGGAGE_BELT_ALERT FlightAlerts = 32
)

var FlightAlerts_name = map[int32]string{
	0:  "NO_ALERTS",
	1:  "ALL_ALERTS",
	2:  "DEPARTURE_GATE_ALERT",
	4:  "DEPARTURE_TIME_ALERT",
	8:  "ARRIVAL_GATE_ALERT",
	16: "ARRIVAL_TIME_ALERT",
	32: "BAGGAGE_BELT_ALERT",
}

var FlightAlerts_value = map[string]int32{
	"NO_ALERTS":            0,
	"ALL_ALERTS":           1,
	"DEPARTURE_GATE_ALERT": 2,
	"DEPARTURE_TIME_ALERT": 4,
	"ARRIVAL_GATE_ALERT":   8,
	"ARRIVAL_TIME_ALERT":   16,
	"BAGGAGE_BELT_ALERT":   32,
}

func (x FlightAlerts) String() string {
	return proto.EnumName(FlightAlerts_name, int32(x))
}

func (FlightAlerts) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0e310730c5d55661, []int{0}
}

// The Boarding Policy is used to determine informational labels on the pass.
type BoardingPolicy int32

const (
	BoardingPolicy_BOARDING_POLICY_UNSPECIFIED BoardingPolicy = 0
	// Boarding is managed by zone.
	BoardingPolicy_ZONE_BASED BoardingPolicy = 1
	// Boarding is managed by group.
	BoardingPolicy_GROUP_BASED BoardingPolicy = 2
	// Another, or No boarding policy is in place.
	BoardingPolicy_BOARDING_POLICY_OTHER BoardingPolicy = 3
)

var BoardingPolicy_name = map[int32]string{
	0: "BOARDING_POLICY_UNSPECIFIED",
	1: "ZONE_BASED",
	2: "GROUP_BASED",
	3: "BOARDING_POLICY_OTHER",
}

var BoardingPolicy_value = map[string]int32{
	"BOARDING_POLICY_UNSPECIFIED": 0,
	"ZONE_BASED":                  1,
	"GROUP_BASED":                 2,
	"BOARDING_POLICY_OTHER":       3,
}

func (x BoardingPolicy) String() string {
	return proto.EnumName(BoardingPolicy_name, int32(x))
}

func (BoardingPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0e310730c5d55661, []int{1}
}

// The Seat Class Policy is used to determine informational labels on the pass.
type SeatClassPolicy int32

const (
	SeatClassPolicy_SEAT_CLASS_POLICY_UNSPECIFIED SeatClassPolicy = 0
	// Seats groups are determined by cabin. "Cabin" will be used as the label on the pass.
	SeatClassPolicy_CABIN_BASED SeatClassPolicy = 1
	// Seats groups are determined by class of travel. "Class" will be used as the label on the pass.
	SeatClassPolicy_CLASS_BASED SeatClassPolicy = 2
	// Seat groups are determined by tier. "Tier" will be used as the label on the pass.
	SeatClassPolicy_TIER_BASED SeatClassPolicy = 3
	// Another, or no seat policy is in place. No label will be used on the pass.
	SeatClassPolicy_SEAT_CLASS_POLICY_OTHER SeatClassPolicy = 4
)

var SeatClassPolicy_name = map[int32]string{
	0: "SEAT_CLASS_POLICY_UNSPECIFIED",
	1: "CABIN_BASED",
	2: "CLASS_BASED",
	3: "TIER_BASED",
	4: "SEAT_CLASS_POLICY_OTHER",
}

var SeatClassPolicy_value = map[string]int32{
	"SEAT_CLASS_POLICY_UNSPECIFIED": 0,
	"CABIN_BASED":                   1,
	"CLASS_BASED":                   2,
	"TIER_BASED":                    3,
	"SEAT_CLASS_POLICY_OTHER":       4,
}

func (x SeatClassPolicy) String() string {
	return proto.EnumName(SeatClassPolicy_name, int32(x))
}

func (SeatClassPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0e310730c5d55661, []int{2}
}

// The authority of an identifier (carrier code, airport code, etc.).
type Authority int32

const (
	// International Air Transport Association (IATA).
	Authority_IATA Authority = 0
	// International Civil Aviation Organization (ICAO).
	Authority_ICAO Authority = 1
)

var Authority_name = map[int32]string{
	0: "IATA",
	1: "ICAO",
}

var Authority_value = map[string]int32{
	"IATA": 0,
	"ICAO": 1,
}

func (x Authority) String() string {
	return proto.EnumName(Authority_name, int32(x))
}

func (Authority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0e310730c5d55661, []int{3}
}

// carrier code and flight number and valid from represent the primary key.
type FlightDesignator struct {
	// The IATA or ICAO carrier code for the flight. In the case of a code-share, this should be the carrier code that you wish to present to the customer. This could be the marketing code, or the operating airline code. A carrier record for this code must exist.
	// @tag: validateGeneric:"required,fixedLenAlphaNum=2|fixedLenAlphaNum=3"
	CarrierCode string `protobuf:"bytes,1,opt,name=carrierCode,proto3" json:"carrierCode,omitempty" validateGeneric:"required,fixedLenAlphaNum=2|fixedLenAlphaNum=3"`
	// The flight number.  Note this number must match the carrier code.
	// @tag: validateGeneric:"required,alphanum,max=5"
	FlightNumber string `protobuf:"bytes,2,opt,name=flightNumber,proto3" json:"flightNumber,omitempty" validateGeneric:"required,alphanum,max=5"`
	// The date that the record is valid from. If not provided, then the date of submission will be used.
	ValidFrom *io.Date `protobuf:"bytes,3,opt,name=validFrom,proto3" json:"validFrom,omitempty"`
	// Multiple designators can be active at a time. Provide a revision to distinguish between versions.
	// @tag: validateGeneric:"required,min=1"
	Revision uint32 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty" validateGeneric:"required,min=1"`
	// Setting to false will prevent further flights to be created against this flight number. Will automatically be set to false if a second designator with a validFrom date before the current date and after this designator's validFrom date is found.
	Active bool `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	// The published flight schedule. If a flight object for a particular departure doesn't exist, these defaults are used. One-off changes to scheduled times for an individual departure should be handled by the Flight object. Long term changes should create a new revision of the FlightDesignator record.
	// @tag: validateGeneric:"required,flight_schedule"
	Schedule *FlightSchedule `protobuf:"bytes,6,opt,name=schedule,proto3" json:"schedule,omitempty" validateGeneric:"required,flight_schedule"`
	// If the flight is operated by a carrier other than the carrierCode supplied, provide the IATA or ICAO carrier code for the operating carrier.  A carrier record must exist.
	// @tag: validateGeneric:"required_with=OperatingFlightNumber,fixedLenAlphaNum=2|fixedLenAlphaNum=3|isdefault"
	OperatingCarrierCode string `protobuf:"bytes,7,opt,name=operatingCarrierCode,proto3" json:"operatingCarrierCode,omitempty" validateGeneric:"required_with=OperatingFlightNumber,fixedLenAlphaNum=2|fixedLenAlphaNum=3|isdefault"`
	// If the flight is operated by a carrier other than the carrierCode supplied, provide the flight number for the operating carrier.
	// @tag: validateGeneric:"required_with=OperatingCarrierCode,alphanum|isdefault,max=5"
	OperatingFlightNumber string `protobuf:"bytes,8,opt,name=operatingFlightNumber,proto3" json:"operatingFlightNumber,omitempty" validateGeneric:"required_with=OperatingCarrierCode,alphanum|isdefault,max=5"`
	// If the flight has code shares, then enter the carrier code and flight number. If there is an operating carrier, then do not include this in the list.  Code share carriers will not be validated.
	// @tag: validateGeneric:"omitempty,max=10,dive,alphanum,max=8"
	CodeShareFlightNumbers []string `protobuf:"bytes,9,rep,name=codeShareFlightNumbers,proto3" json:"codeShareFlightNumbers,omitempty" validateGeneric:"omitempty,max=10,dive,alphanum,max=8"`
	// The origin port of the flight. In the case of direct flights with multiple stops, this will represent the port where the route commences.
	// @tag: validateGeneric:"required,fixedLenAlphaNum=3|fixedLenAlphaNum=4"
	Origin string `protobuf:"bytes,10,opt,name=origin,proto3" json:"origin,omitempty" validateGeneric:"required,fixedLenAlphaNum=3|fixedLenAlphaNum=4"`
	// The destination port of the flight. In the case of direct flights with multiple stops, this will represent the final port where the route terminates.
	// @tag: validateGeneric:"required,fixedLenAlphaNum=3|fixedLenAlphaNum=4"
	Destination string `protobuf:"bytes,11,opt,name=destination,proto3" json:"destination,omitempty" validateGeneric:"required,fixedLenAlphaNum=3|fixedLenAlphaNum=4"`
	// In the case of multiple stops, an ordered array of transit points, commencing with the first port after the origin and ending with the penultimate port.
	// @tag: validateGeneric:"omitempty,dive,fixedLenAlphaNum=3|fixedLenAlphaNum=4"
	TransitPoints []string `protobuf:"bytes,12,rep,name=transitPoints,proto3" json:"transitPoints,omitempty" validateGeneric:"omitempty,dive,fixedLenAlphaNum=3|fixedLenAlphaNum=4"`
	// The default terminal that the flight departs from.
	DepartureTerminal string `protobuf:"bytes,13,opt,name=departureTerminal,proto3" json:"departureTerminal,omitempty"`
	// The default terminal of the final destination.
	ArrivalTerminal string `protobuf:"bytes,14,opt,name=arrivalTerminal,proto3" json:"arrivalTerminal,omitempty"`
	// In the case of multiple stops, an ordered array of transit terminals. The length of this array should match the number of transit points.
	TransitTerminals []string `protobuf:"bytes,15,rep,name=transitTerminals,proto3" json:"transitTerminals,omitempty"`
	// The Boarding Policy is used to determine informational labels on the pass.
	BoardingPolicy BoardingPolicy `protobuf:"varint,16,opt,name=boardingPolicy,proto3,enum=flights.BoardingPolicy" json:"boardingPolicy,omitempty"`
	// The Seat Class Policy is used to determine informational labels on the pass.
	SeatClassPolicy SeatClassPolicy `protobuf:"varint,17,opt,name=seatClassPolicy,proto3,enum=flights.SeatClassPolicy" json:"seatClassPolicy,omitempty"`
	// An array of alerts to subscribe to for the flight. Note that additional charges apply.
	Alerts []FlightAlerts `protobuf:"varint,18,rep,packed,name=alerts,proto3,enum=flights.FlightAlerts" json:"alerts,omitempty"`
	// The PassKit template id that will be used for boarding passes for this flight. It can be overwritten at the flight level.
	// @tag: validateGeneric:"required,uuidCompressedString"
	PassTemplateId string `protobuf:"bytes,19,opt,name=passTemplateId,proto3" json:"passTemplateId,omitempty" validateGeneric:"required,uuidCompressedString"`
	// Minutes after estimated or scheduled arrival to automatically invalidate the pass. Enter -1 if the pass should not auto invalidate. Default is 48 hours.
	AutoInvalidateAfter uint32 `protobuf:"varint,20,opt,name=autoInvalidateAfter,proto3" json:"autoInvalidateAfter,omitempty"`
	// Invalidate passes where either the booking or the flight have been cancelled. Default is true.
	AutoInvalidateCancelledPasses bool `protobuf:"varint,21,opt,name=autoInvalidateCancelledPasses,proto3" json:"autoInvalidateCancelledPasses,omitempty"`
	// A list of up to 10 GPS locations where this boarding pass should be presented on the lock-screen.
	// @tag: validateGeneric:"omitempty,dive" validateCreate:"omitempty,dive" validateUpdate:"omitempty,dive"
	LocationMessages []*io.GPSLocation `protobuf:"bytes,22,rep,name=locationMessages,proto3" json:"locationMessages,omitempty" validateGeneric:"omitempty,dive" validateCreate:"omitempty,dive" validateUpdate:"omitempty,dive"`
	// A list of up to 10 Beacon UUIDs that should trigger the boarding pass to be presented on the lock-screen.
	// @tag: validateGeneric:"omitempty,dive" validateCreate:"omitempty,dive" validateUpdate:"omitempty,dive"
	BeaconMessages []*io.Beacon `protobuf:"bytes,23,rep,name=beaconMessages,proto3" json:"beaconMessages,omitempty" validateGeneric:"omitempty,dive" validateCreate:"omitempty,dive" validateUpdate:"omitempty,dive"`
	// A list of links to be appended to the end of each boarding pass.
	// @tag: validateGeneric:"omitempty,dive" validateCreate:"omitempty,dive" validateUpdate:"omitempty,dive"
	DefaultLinks []*io.Link `protobuf:"bytes,24,rep,name=defaultLinks,proto3" json:"defaultLinks,omitempty" validateGeneric:"omitempty,dive" validateCreate:"omitempty,dive" validateUpdate:"omitempty,dive"`
	// If PassKit are generating barcodes, include conditional items. Default false.
	ConditionalItems bool `protobuf:"varint,25,opt,name=ConditionalItems,proto3" json:"ConditionalItems,omitempty"`
	// If PassKit are generating barcodes, default airline use data (IATA item 4). This can be overwritten at the flight and boarding pass level.
	BarcodeAdditionalData string   `protobuf:"bytes,26,opt,name=BarcodeAdditionalData,proto3" json:"BarcodeAdditionalData,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *FlightDesignator) Reset()         { *m = FlightDesignator{} }
func (m *FlightDesignator) String() string { return proto.CompactTextString(m) }
func (*FlightDesignator) ProtoMessage()    {}
func (*FlightDesignator) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e310730c5d55661, []int{0}
}

func (m *FlightDesignator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlightDesignator.Unmarshal(m, b)
}
func (m *FlightDesignator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlightDesignator.Marshal(b, m, deterministic)
}
func (m *FlightDesignator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlightDesignator.Merge(m, src)
}
func (m *FlightDesignator) XXX_Size() int {
	return xxx_messageInfo_FlightDesignator.Size(m)
}
func (m *FlightDesignator) XXX_DiscardUnknown() {
	xxx_messageInfo_FlightDesignator.DiscardUnknown(m)
}

var xxx_messageInfo_FlightDesignator proto.InternalMessageInfo

func (m *FlightDesignator) GetCarrierCode() string {
	if m != nil {
		return m.CarrierCode
	}
	return ""
}

func (m *FlightDesignator) GetFlightNumber() string {
	if m != nil {
		return m.FlightNumber
	}
	return ""
}

func (m *FlightDesignator) GetValidFrom() *io.Date {
	if m != nil {
		return m.ValidFrom
	}
	return nil
}

func (m *FlightDesignator) GetRevision() uint32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *FlightDesignator) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *FlightDesignator) GetSchedule() *FlightSchedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

func (m *FlightDesignator) GetOperatingCarrierCode() string {
	if m != nil {
		return m.OperatingCarrierCode
	}
	return ""
}

func (m *FlightDesignator) GetOperatingFlightNumber() string {
	if m != nil {
		return m.OperatingFlightNumber
	}
	return ""
}

func (m *FlightDesignator) GetCodeShareFlightNumbers() []string {
	if m != nil {
		return m.CodeShareFlightNumbers
	}
	return nil
}

func (m *FlightDesignator) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *FlightDesignator) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *FlightDesignator) GetTransitPoints() []string {
	if m != nil {
		return m.TransitPoints
	}
	return nil
}

func (m *FlightDesignator) GetDepartureTerminal() string {
	if m != nil {
		return m.DepartureTerminal
	}
	return ""
}

func (m *FlightDesignator) GetArrivalTerminal() string {
	if m != nil {
		return m.ArrivalTerminal
	}
	return ""
}

func (m *FlightDesignator) GetTransitTerminals() []string {
	if m != nil {
		return m.TransitTerminals
	}
	return nil
}

func (m *FlightDesignator) GetBoardingPolicy() BoardingPolicy {
	if m != nil {
		return m.BoardingPolicy
	}
	return BoardingPolicy_BOARDING_POLICY_UNSPECIFIED
}

func (m *FlightDesignator) GetSeatClassPolicy() SeatClassPolicy {
	if m != nil {
		return m.SeatClassPolicy
	}
	return SeatClassPolicy_SEAT_CLASS_POLICY_UNSPECIFIED
}

func (m *FlightDesignator) GetAlerts() []FlightAlerts {
	if m != nil {
		return m.Alerts
	}
	return nil
}

func (m *FlightDesignator) GetPassTemplateId() string {
	if m != nil {
		return m.PassTemplateId
	}
	return ""
}

func (m *FlightDesignator) GetAutoInvalidateAfter() uint32 {
	if m != nil {
		return m.AutoInvalidateAfter
	}
	return 0
}

func (m *FlightDesignator) GetAutoInvalidateCancelledPasses() bool {
	if m != nil {
		return m.AutoInvalidateCancelledPasses
	}
	return false
}

func (m *FlightDesignator) GetLocationMessages() []*io.GPSLocation {
	if m != nil {
		return m.LocationMessages
	}
	return nil
}

func (m *FlightDesignator) GetBeaconMessages() []*io.Beacon {
	if m != nil {
		return m.BeaconMessages
	}
	return nil
}

func (m *FlightDesignator) GetDefaultLinks() []*io.Link {
	if m != nil {
		return m.DefaultLinks
	}
	return nil
}

func (m *FlightDesignator) GetConditionalItems() bool {
	if m != nil {
		return m.ConditionalItems
	}
	return false
}

func (m *FlightDesignator) GetBarcodeAdditionalData() string {
	if m != nil {
		return m.BarcodeAdditionalData
	}
	return ""
}

type FlightDesignatorRequest struct {
	// The IATA or ICAO carrier code for the flight.
	CarrierCode string `protobuf:"bytes,1,opt,name=carrierCode,proto3" json:"carrierCode,omitempty"`
	// The flight number.
	FlightNumber string `protobuf:"bytes,2,opt,name=flightNumber,proto3" json:"flightNumber,omitempty"`
	// Revision. Each designator record requires a version number.
	Revision             uint32   `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlightDesignatorRequest) Reset()         { *m = FlightDesignatorRequest{} }
func (m *FlightDesignatorRequest) String() string { return proto.CompactTextString(m) }
func (*FlightDesignatorRequest) ProtoMessage()    {}
func (*FlightDesignatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e310730c5d55661, []int{1}
}

func (m *FlightDesignatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlightDesignatorRequest.Unmarshal(m, b)
}
func (m *FlightDesignatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlightDesignatorRequest.Marshal(b, m, deterministic)
}
func (m *FlightDesignatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlightDesignatorRequest.Merge(m, src)
}
func (m *FlightDesignatorRequest) XXX_Size() int {
	return xxx_messageInfo_FlightDesignatorRequest.Size(m)
}
func (m *FlightDesignatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FlightDesignatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FlightDesignatorRequest proto.InternalMessageInfo

func (m *FlightDesignatorRequest) GetCarrierCode() string {
	if m != nil {
		return m.CarrierCode
	}
	return ""
}

func (m *FlightDesignatorRequest) GetFlightNumber() string {
	if m != nil {
		return m.FlightNumber
	}
	return ""
}

func (m *FlightDesignatorRequest) GetRevision() uint32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

// If there are no departures on a given day (E.g. flight only operates on Tuesdays and Thursdays), the days with no departures should be nil.
type FlightSchedule struct {
	// @tag: validateGeneric:"required_without_all=Tuesday Wednesday Thursday Friday Saturday Sunday"
	Monday               *FlightTimes `protobuf:"bytes,1,opt,name=monday,proto3" json:"monday,omitempty" validateGeneric:"required_without_all=Tuesday Wednesday Thursday Friday Saturday Sunday"`
	Tuesday              *FlightTimes `protobuf:"bytes,2,opt,name=tuesday,proto3" json:"tuesday,omitempty"`
	Wednesday            *FlightTimes `protobuf:"bytes,3,opt,name=wednesday,proto3" json:"wednesday,omitempty"`
	Thursday             *FlightTimes `protobuf:"bytes,4,opt,name=thursday,proto3" json:"thursday,omitempty"`
	Friday               *FlightTimes `protobuf:"bytes,5,opt,name=friday,proto3" json:"friday,omitempty"`
	Saturday             *FlightTimes `protobuf:"bytes,6,opt,name=saturday,proto3" json:"saturday,omitempty"`
	Sunday               *FlightTimes `protobuf:"bytes,7,opt,name=sunday,proto3" json:"sunday,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FlightSchedule) Reset()         { *m = FlightSchedule{} }
func (m *FlightSchedule) String() string { return proto.CompactTextString(m) }
func (*FlightSchedule) ProtoMessage()    {}
func (*FlightSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e310730c5d55661, []int{2}
}

func (m *FlightSchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlightSchedule.Unmarshal(m, b)
}
func (m *FlightSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlightSchedule.Marshal(b, m, deterministic)
}
func (m *FlightSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlightSchedule.Merge(m, src)
}
func (m *FlightSchedule) XXX_Size() int {
	return xxx_messageInfo_FlightSchedule.Size(m)
}
func (m *FlightSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_FlightSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_FlightSchedule proto.InternalMessageInfo

func (m *FlightSchedule) GetMonday() *FlightTimes {
	if m != nil {
		return m.Monday
	}
	return nil
}

func (m *FlightSchedule) GetTuesday() *FlightTimes {
	if m != nil {
		return m.Tuesday
	}
	return nil
}

func (m *FlightSchedule) GetWednesday() *FlightTimes {
	if m != nil {
		return m.Wednesday
	}
	return nil
}

func (m *FlightSchedule) GetThursday() *FlightTimes {
	if m != nil {
		return m.Thursday
	}
	return nil
}

func (m *FlightSchedule) GetFriday() *FlightTimes {
	if m != nil {
		return m.Friday
	}
	return nil
}

func (m *FlightSchedule) GetSaturday() *FlightTimes {
	if m != nil {
		return m.Saturday
	}
	return nil
}

func (m *FlightSchedule) GetSunday() *FlightTimes {
	if m != nil {
		return m.Sunday
	}
	return nil
}

type FlightTimes struct {
	// The published departure time.
	// @tag: validateGeneric:"required"
	ScheduledDepartureTime *io.Time `protobuf:"bytes,1,opt,name=scheduledDepartureTime,proto3" json:"scheduledDepartureTime,omitempty" validateGeneric:"required"`
	// The published boarding time.
	BoardingTime *io.Time `protobuf:"bytes,2,opt,name=boardingTime,proto3" json:"boardingTime,omitempty"`
	// The point after which passengers will be denied boarding.
	GateClosingTime *io.Time `protobuf:"bytes,3,opt,name=gateClosingTime,proto3" json:"gateClosingTime,omitempty"`
	// The published, scheduled arrival time.
	ScheduledArrivalTime *io.Time `protobuf:"bytes,4,opt,name=scheduledArrivalTime,proto3" json:"scheduledArrivalTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlightTimes) Reset()         { *m = FlightTimes{} }
func (m *FlightTimes) String() string { return proto.CompactTextString(m) }
func (*FlightTimes) ProtoMessage()    {}
func (*FlightTimes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e310730c5d55661, []int{3}
}

func (m *FlightTimes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlightTimes.Unmarshal(m, b)
}
func (m *FlightTimes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlightTimes.Marshal(b, m, deterministic)
}
func (m *FlightTimes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlightTimes.Merge(m, src)
}
func (m *FlightTimes) XXX_Size() int {
	return xxx_messageInfo_FlightTimes.Size(m)
}
func (m *FlightTimes) XXX_DiscardUnknown() {
	xxx_messageInfo_FlightTimes.DiscardUnknown(m)
}

var xxx_messageInfo_FlightTimes proto.InternalMessageInfo

func (m *FlightTimes) GetScheduledDepartureTime() *io.Time {
	if m != nil {
		return m.ScheduledDepartureTime
	}
	return nil
}

func (m *FlightTimes) GetBoardingTime() *io.Time {
	if m != nil {
		return m.BoardingTime
	}
	return nil
}

func (m *FlightTimes) GetGateClosingTime() *io.Time {
	if m != nil {
		return m.GateClosingTime
	}
	return nil
}

func (m *FlightTimes) GetScheduledArrivalTime() *io.Time {
	if m != nil {
		return m.ScheduledArrivalTime
	}
	return nil
}

func init() {
	proto.RegisterEnum("flights.FlightAlerts", FlightAlerts_name, FlightAlerts_value)
	proto.RegisterEnum("flights.BoardingPolicy", BoardingPolicy_name, BoardingPolicy_value)
	proto.RegisterEnum("flights.SeatClassPolicy", SeatClassPolicy_name, SeatClassPolicy_value)
	proto.RegisterEnum("flights.Authority", Authority_name, Authority_value)
	proto.RegisterType((*FlightDesignator)(nil), "flights.FlightDesignator")
	proto.RegisterType((*FlightDesignatorRequest)(nil), "flights.FlightDesignatorRequest")
	proto.RegisterType((*FlightSchedule)(nil), "flights.FlightSchedule")
	proto.RegisterType((*FlightTimes)(nil), "flights.FlightTimes")
}

func init() {
	proto.RegisterFile("io/flights/flight_designator.proto", fileDescriptor_0e310730c5d55661)
}

var fileDescriptor_0e310730c5d55661 = []byte{
	// 1403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x6e, 0x1b, 0x37,
	0x16, 0xce, 0x48, 0xb6, 0x2c, 0x1d, 0xd9, 0x92, 0xc2, 0xf8, 0x67, 0xec, 0x20, 0x9b, 0x89, 0x11,
	0x04, 0x5a, 0xc1, 0x96, 0x02, 0x25, 0xd8, 0xcd, 0x3a, 0x8b, 0xdd, 0x1d, 0xfd, 0xd8, 0x2b, 0x44,
	0xb1, 0x84, 0x91, 0xbc, 0xc0, 0xba, 0x68, 0x05, 0x7a, 0x86, 0x96, 0xd9, 0x8c, 0x86, 0x2e, 0x49,
	0x39, 0x76, 0x8b, 0x00, 0x05, 0x7a, 0xd7, 0xde, 0xf9, 0x09, 0x7a, 0xdb, 0x3e, 0x4a, 0x81, 0x5e,
	0xd4, 0x8f, 0xd0, 0x17, 0xe8, 0x6d, 0x2f, 0x8b, 0xa1, 0x46, 0xd2, 0x68, 0xec, 0xe8, 0xa2, 0x57,
	0x63, 0x9e, 0xef, 0xfb, 0x0e, 0xc9, 0xc3, 0xc3, 0x8f, 0x32, 0x6c, 0x53, 0x56, 0x3a, 0x75, 0x69,
	0xff, 0x4c, 0x8a, 0xe0, 0xdb, 0x73, 0x88, 0xa0, 0x7d, 0x0f, 0x4b, 0xc6, 0x8b, 0xe7, 0x9c, 0x49,
	0x86, 0x96, 0x02, 0xc2, 0xd6, 0x5f, 0x28, 0x2b, 0xd9, 0x6c, 0x30, 0x60, 0x5e, 0xf0, 0xe9, 0xb1,
	0x93, 0xcf, 0x89, 0x2d, 0xc5, 0x88, 0xb8, 0xb5, 0x39, 0xc5, 0xcf, 0x39, 0xbb, 0xa4, 0x03, 0x2a,
	0xaf, 0x02, 0x68, 0x6d, 0x0a, 0xb9, 0xd4, 0x7b, 0x37, 0x56, 0xec, 0xa8, 0x8f, 0xbd, 0xdb, 0x27,
	0xde, 0xae, 0x78, 0x8f, 0xfb, 0x7d, 0xc2, 0x4b, 0xec, 0x5c, 0x52, 0xe6, 0x89, 0x12, 0xf6, 0x3c,
	0x26, 0xb1, 0xfa, 0x7b, 0xc4, 0xde, 0xfe, 0x3d, 0x0d, 0xb9, 0x7d, 0xb5, 0x96, 0xda, 0x64, 0x8d,
	0xe8, 0xef, 0x90, 0xb6, 0x31, 0xe7, 0x94, 0xf0, 0x2a, 0x73, 0x88, 0xae, 0x19, 0x5a, 0x3e, 0x55,
	0x59, 0xbb, 0x36, 0xd1, 0xb7, 0x5a, 0xf6, 0xb3, 0x4f, 0xcc, 0xdd, 0xe3, 0xe7, 0xbb, 0xff, 0xf8,
	0xf4, 0xab, 0x17, 0x3b, 0x2f, 0x3f, 0x3c, 0xb5, 0xc2, 0x4c, 0xf4, 0x57, 0x58, 0x1e, 0x6d, 0xec,
	0x70, 0x38, 0x38, 0x21, 0x5c, 0x8f, 0x29, 0xe5, 0xe2, 0xb5, 0x19, 0xbb, 0x5c, 0xb4, 0x66, 0x20,
	0xf4, 0x0c, 0x52, 0x17, 0xd8, 0xa5, 0xce, 0x3e, 0x67, 0x03, 0x3d, 0x6e, 0x68, 0xf9, 0x74, 0x39,
	0x59, 0xa4, 0xac, 0x58, 0xc3, 0x92, 0x58, 0x53, 0x08, 0x6d, 0x41, 0x92, 0x93, 0x0b, 0x2a, 0x28,
	0xf3, 0xf4, 0x05, 0x43, 0xcb, 0xaf, 0x58, 0x93, 0x31, 0x7a, 0x02, 0x09, 0x6c, 0x4b, 0x7a, 0x41,
	0xf4, 0x45, 0x43, 0xcb, 0x27, 0x2b, 0xa9, 0x6b, 0x33, 0xb1, 0xb7, 0xd0, 0xb5, 0x8e, 0xea, 0x56,
	0x00, 0xa0, 0x17, 0x90, 0x14, 0xf6, 0x19, 0x71, 0x86, 0x2e, 0xd1, 0x13, 0x6a, 0x96, 0x8d, 0x62,
	0x50, 0xfb, 0xe2, 0x68, 0xdf, 0x9d, 0x00, 0xb6, 0x26, 0x44, 0xf4, 0x4f, 0x58, 0x65, 0xe7, 0x84,
	0x63, 0x49, 0xbd, 0x7e, 0x35, 0x54, 0x88, 0x25, 0xb5, 0x9d, 0xe4, 0xb5, 0xb9, 0x78, 0x19, 0xff,
	0x5a, 0x8b, 0x59, 0x77, 0xb2, 0xd0, 0x6b, 0x58, 0x9b, 0xc4, 0xf7, 0xc3, 0xd5, 0x48, 0x86, 0xab,
	0x71, 0x37, 0x07, 0xfd, 0x0d, 0xd6, 0x6d, 0xe6, 0x90, 0xce, 0x19, 0xe6, 0x24, 0x0c, 0x08, 0x3d,
	0x65, 0xc4, 0xf3, 0x29, 0xeb, 0x23, 0x28, 0x5a, 0x87, 0x04, 0xe3, 0xb4, 0x4f, 0x3d, 0x1d, 0xfc,
	0x59, 0xac, 0x60, 0x84, 0x0c, 0x48, 0x3b, 0x44, 0x48, 0xea, 0xa9, 0x53, 0xd7, 0xd3, 0x0a, 0x0c,
	0x87, 0xd0, 0x53, 0x58, 0x91, 0x1c, 0x7b, 0x82, 0xca, 0x36, 0xa3, 0x9e, 0x14, 0xfa, 0xb2, 0x9a,
	0x68, 0x36, 0x88, 0x76, 0xe0, 0xbe, 0x43, 0xce, 0x31, 0x97, 0x43, 0x4e, 0xba, 0x84, 0x0f, 0xa8,
	0x87, 0x5d, 0x7d, 0x45, 0x65, 0xbb, 0x0d, 0xa0, 0x3c, 0x64, 0xfd, 0x82, 0x5c, 0x60, 0x77, 0xc2,
	0xcd, 0x28, 0x6e, 0x34, 0x8c, 0x0a, 0x90, 0x0b, 0x26, 0x1a, 0x87, 0x84, 0x9e, 0x55, 0x0b, 0xb8,
	0x15, 0x47, 0xff, 0x86, 0xcc, 0x09, 0xc3, 0xdc, 0xa1, 0x5e, 0xbf, 0xcd, 0x5c, 0x6a, 0x5f, 0xe9,
	0x39, 0x43, 0xcb, 0x67, 0x42, 0x27, 0x5a, 0x99, 0x81, 0xad, 0x08, 0x1d, 0x55, 0x20, 0x2b, 0x08,
	0x96, 0x55, 0x17, 0x0b, 0x11, 0x64, 0xb8, 0xaf, 0x32, 0xe8, 0x93, 0x0c, 0x9d, 0x59, 0xdc, 0x8a,
	0x0a, 0xd0, 0x2e, 0x24, 0xb0, 0x4b, 0xb8, 0x14, 0x3a, 0x32, 0xe2, 0xf9, 0x4c, 0x79, 0x2d, 0xd2,
	0x4e, 0xa6, 0x02, 0xad, 0x80, 0x84, 0x9e, 0x41, 0xe6, 0x1c, 0x0b, 0xd1, 0x25, 0x83, 0x73, 0x17,
	0x4b, 0xd2, 0x70, 0xf4, 0x07, 0xaa, 0x10, 0x91, 0x28, 0x7a, 0x0d, 0x0f, 0xf0, 0x50, 0xb2, 0x86,
	0xa7, 0x3a, 0x1f, 0x4b, 0x62, 0x9e, 0x4a, 0xc2, 0xf5, 0x55, 0xbf, 0xe3, 0x83, 0xbe, 0x2e, 0xbf,
	0x7a, 0xf5, 0xdc, 0xba, 0x8b, 0x85, 0x5a, 0xf0, 0x68, 0x36, 0x5c, 0xc5, 0x9e, 0x4d, 0x5c, 0x97,
	0x38, 0x6d, 0x2c, 0x04, 0x11, 0xfa, 0x5a, 0xf4, 0x7a, 0xcc, 0xe7, 0xa3, 0x2a, 0xe4, 0x5c, 0x66,
	0xab, 0xfe, 0x78, 0x4b, 0x84, 0xc0, 0x7d, 0x22, 0xf4, 0x75, 0x23, 0x9e, 0x4f, 0x97, 0xb3, 0xfe,
	0x1d, 0x3d, 0x68, 0x77, 0x9a, 0x01, 0x5c, 0x49, 0x5c, 0x9b, 0xf1, 0xef, 0x35, 0xb0, 0x6e, 0x09,
	0xd0, 0x1e, 0x64, 0x4e, 0x08, 0xb6, 0x43, 0x29, 0x36, 0x54, 0x0a, 0xf0, 0x53, 0x54, 0x14, 0x32,
	0x51, 0x47, 0x98, 0x68, 0x07, 0x96, 0x1d, 0x72, 0x8a, 0x87, 0xae, 0x6c, 0xfa, 0xd6, 0xa6, 0xeb,
	0x4a, 0xa9, 0x0c, 0xc2, 0x0f, 0x58, 0x33, 0xa8, 0xdf, 0x44, 0x55, 0xe6, 0x39, 0xd4, 0x9f, 0x1e,
	0xbb, 0x0d, 0x49, 0x06, 0x42, 0xdf, 0xf4, 0xb7, 0x6c, 0xdd, 0x8a, 0xa3, 0x97, 0xb0, 0x56, 0xc1,
	0xdc, 0xbf, 0x45, 0xa6, 0x33, 0x46, 0x6a, 0x58, 0x62, 0x7d, 0x4b, 0x9d, 0xcb, 0xdd, 0xe0, 0xde,
	0x2f, 0xda, 0xb5, 0xf9, 0xb3, 0x06, 0x3f, 0x69, 0x85, 0xfb, 0xa3, 0x63, 0x36, 0xa6, 0x76, 0x59,
	0x3e, 0x36, 0x8d, 0x51, 0x0f, 0x18, 0x53, 0x9f, 0x37, 0x38, 0xb1, 0x19, 0x77, 0xfc, 0x88, 0xcd,
	0xe9, 0x09, 0x11, 0xc6, 0x80, 0x09, 0xe9, 0x5e, 0x19, 0xc2, 0xf7, 0x5f, 0xdb, 0x70, 0xb0, 0xc4,
	0xc6, 0x7b, 0x2a, 0xcf, 0x0c, 0x4e, 0xfa, 0x98, 0x3b, 0x86, 0x64, 0x06, 0x1e, 0xa7, 0x09, 0xac,
	0x81, 0x79, 0xc5, 0x1b, 0x2d, 0xec, 0xaf, 0x37, 0xda, 0x8c, 0x87, 0xde, 0x68, 0xc1, 0x2d, 0xbf,
	0xd1, 0x26, 0xde, 0x75, 0xa3, 0x4d, 0xec, 0xf1, 0x46, 0x0b, 0xdf, 0xf3, 0x1b, 0x2d, 0xd2, 0x72,
	0xdb, 0xdf, 0xc5, 0x60, 0x23, 0x6a, 0xfd, 0x16, 0xf9, 0x62, 0x48, 0x84, 0x44, 0x85, 0xbb, 0x5e,
	0x80, 0xa9, 0xf1, 0xfd, 0x59, 0xd3, 0x0f, 0x9b, 0x79, 0x7c, 0xd6, 0xcc, 0xf7, 0x3e, 0x5c, 0x9b,
	0x5f, 0xc2, 0x65, 0x61, 0xf3, 0x56, 0x7d, 0x8d, 0x60, 0x51, 0xe5, 0x7f, 0x1d, 0x09, 0xe2, 0x18,
	0xa7, 0xaa, 0xb8, 0x92, 0x53, 0x72, 0x41, 0xbd, 0xbe, 0xe1, 0x10, 0x89, 0xa9, 0x2b, 0x0c, 0x76,
	0x6a, 0x60, 0xc3, 0xf7, 0x21, 0x6a, 0x0f, 0x5d, 0xcc, 0x6f, 0x9f, 0xc8, 0xfc, 0x5a, 0x6e, 0xff,
	0x1a, 0x83, 0xcc, 0xec, 0x83, 0x80, 0x76, 0x20, 0x31, 0x60, 0x9e, 0x83, 0xaf, 0xd4, 0xfe, 0xd3,
	0xe5, 0xd5, 0xc8, 0x55, 0xef, 0xd2, 0x01, 0x11, 0x56, 0xc0, 0x41, 0x45, 0x58, 0x92, 0x43, 0x22,
	0x7c, 0x7a, 0x6c, 0x0e, 0x7d, 0x4c, 0x42, 0x65, 0x48, 0xbd, 0x27, 0x8e, 0x37, 0x52, 0xc4, 0xe7,
	0x28, 0xa6, 0x34, 0xf4, 0x1c, 0x92, 0xf2, 0x6c, 0xc8, 0x95, 0x64, 0x61, 0x8e, 0x64, 0xc2, 0xf2,
	0xf7, 0x70, 0xca, 0xa9, 0xcf, 0x5f, 0x9c, 0xb7, 0x87, 0x11, 0xc7, 0xcf, 0x2f, 0xb0, 0x1c, 0x72,
	0x9f, 0x9f, 0x98, 0x97, 0x7f, 0xcc, 0xf2, 0xf3, 0x8b, 0xa1, 0xaa, 0xd1, 0xd2, 0xbc, 0xfc, 0x23,
	0xce, 0xf6, 0x6f, 0x1a, 0xa4, 0x43, 0x71, 0xf4, 0x1f, 0x58, 0x1f, 0x37, 0xae, 0x53, 0x9b, 0xbc,
	0x22, 0x74, 0x40, 0x82, 0x8a, 0xab, 0x0b, 0xef, 0x8f, 0xad, 0x8f, 0xf0, 0x7c, 0xa3, 0x18, 0x9b,
	0xbc, 0xd2, 0xc5, 0x22, 0xba, 0x19, 0x14, 0x95, 0x21, 0xdb, 0xf7, 0xed, 0xce, 0x65, 0x62, 0x2c,
	0x88, 0x47, 0x04, 0x51, 0x82, 0xff, 0x63, 0x60, 0x32, 0xb7, 0x19, 0xbc, 0x5e, 0xbe, 0x70, 0x21,
	0x22, 0xbc, 0x93, 0x55, 0xf8, 0x41, 0x83, 0xe5, 0xf0, 0xc3, 0x80, 0x56, 0x20, 0x75, 0xd8, 0xea,
	0x99, 0xcd, 0xba, 0xd5, 0xed, 0xe4, 0xee, 0xa1, 0x0c, 0x80, 0xd9, 0x6c, 0x8e, 0xc7, 0x1a, 0xd2,
	0x61, 0xb5, 0x56, 0x6f, 0x9b, 0x56, 0xf7, 0xc8, 0xaa, 0xf7, 0x0e, 0xcc, 0x6e, 0x7d, 0x04, 0xe5,
	0x62, 0xb3, 0x48, 0xb7, 0xf1, 0x76, 0x8c, 0x2c, 0xa0, 0x75, 0x40, 0xa6, 0x65, 0x35, 0xfe, 0x67,
	0x36, 0xc3, 0x8a, 0x64, 0x38, 0x1e, 0xe2, 0xe7, 0xfc, 0x78, 0xc5, 0x3c, 0x38, 0x30, 0x0f, 0xea,
	0xbd, 0x4a, 0xbd, 0xd9, 0x0d, 0xe2, 0x46, 0x61, 0x00, 0x99, 0xd9, 0x07, 0x14, 0x3d, 0x86, 0x87,
	0x95, 0x96, 0x69, 0xd5, 0x1a, 0x87, 0x07, 0xbd, 0x76, 0xab, 0xd9, 0xa8, 0xfe, 0xbf, 0x77, 0x74,
	0xd8, 0x69, 0xd7, 0xab, 0x8d, 0xfd, 0x46, 0xbd, 0x36, 0x5a, 0xfe, 0x71, 0xeb, 0xb0, 0xde, 0xab,
	0x98, 0x9d, 0x7a, 0x2d, 0xa7, 0xa1, 0x2c, 0xa4, 0x0f, 0xac, 0xd6, 0x51, 0x3b, 0x08, 0xc4, 0xd0,
	0x26, 0xac, 0x45, 0x33, 0xb4, 0xba, 0xff, 0xad, 0x5b, 0xb9, 0x78, 0xe1, 0x1b, 0x0d, 0xb2, 0x91,
	0xe7, 0x16, 0x3d, 0x81, 0x47, 0x9d, 0xba, 0xd9, 0xed, 0x55, 0x9b, 0x66, 0xa7, 0x73, 0xf7, 0x94,
	0x59, 0x48, 0x57, 0xcd, 0x4a, 0xe3, 0x30, 0x3c, 0xe7, 0x88, 0x3e, 0x9e, 0x33, 0x03, 0xd0, 0x6d,
	0xd4, 0xad, 0x60, 0x1c, 0x47, 0x0f, 0x61, 0xe3, 0x76, 0xd2, 0xd1, 0x2a, 0x16, 0x0a, 0x8f, 0x21,
	0x65, 0x0e, 0xe5, 0x19, 0xe3, 0x54, 0x5e, 0xa1, 0x24, 0x2c, 0x34, 0xcc, 0xae, 0x99, 0xbb, 0xa7,
	0xfe, 0xaa, 0x9a, 0xad, 0x9c, 0x56, 0xe9, 0xc0, 0x06, 0x65, 0x45, 0xdf, 0x3b, 0xdf, 0x51, 0x59,
	0x6c, 0xbf, 0xa1, 0x2c, 0x68, 0x6d, 0x71, 0xbc, 0x23, 0x24, 0x16, 0x67, 0x13, 0xcc, 0x66, 0x83,
	0x12, 0x65, 0xa5, 0x01, 0x73, 0x88, 0x5b, 0x12, 0xce, 0xbb, 0x52, 0x9f, 0x95, 0xa6, 0xff, 0x0b,
	0xfc, 0x18, 0x4b, 0xb5, 0xdf, 0x04, 0xca, 0x93, 0x84, 0xfa, 0xf5, 0xfd, 0xe2, 0x8f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xef, 0xf0, 0xd2, 0x5a, 0x2c, 0x0c, 0x00, 0x00,
}
